### ISSUE TITLE
Calendar failes to load events

### ISSUE THREAD

**Issue by manem02** [TUM-Dev/Campus-UWP#22]
## Description

hey guys,  when I open the campus TUM-App on my desktop (Windows 11) it doesn´t show the calendar events; it says: "Failed to load calendar events. Internal error. Please retry...". I have reestablished the Tokens but it still won´t work. Looking forward to ur answer :D

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* App Version(s): v.X.Y.Z 
* Device form factor (Desktop, Mobile, Xbox, Surface Hub, ...):
* Where did you get it from (e.g. Store, Sideload, git, ...):
* Operating System and version:

**Comment by COM8** [comment]
Thanks for taking the time to report this issue!
Could you please upload your `logs.zip` here, like shown bellow:
![Export Logs](https://user-images.githubusercontent.com/11741404/176376698-23c970b0-576e-44f3-b62a-b007ccb2f366.gif)

**Comment by COM8** [comment]
Closing for no response.
