### ISSUE TITLE
Tuition Fee Displayed Incorrectly

### ISSUE THREAD

**Issue by Saydemr** [TUM-Dev/Campus-UWP#24]
## Description

Normally on TUMOnline, summer semester fee amount is €152.30, and it is displayed as follows (in English language setting).

![image](https://user-images.githubusercontent.com/37012364/203869009-cc30e3b1-dff0-4fde-9839-6f347e14822a.png)

On the other hand, TUM-Campus app displays 100x the amount possibly because of separator mismatch between German and English.

![image](https://user-images.githubusercontent.com/37012364/203869199-208e13df-6a4c-4a97-98b6-2a416b2875ca.png)

## Expected Behavior

Displayed amount is the same as the amount on TUMOnline

## Actual Behavior

Displayed amount is 100x the actual amount

## Possible Fix

Problems with separator interpretation (comma or dot)

## Steps to Reproduce

1. Open TUM-Campus app on Windows.
2. Head to Tuition Fees from the left panel.

## Context

This panicked me to think that Bavarian government was too quick introducing the new law that requires international students to pay additional fees.

## Your Environment

* App Version(s): v.2.4.0.0 
* Device form factor: Desktop
* Where did you get it from: Microsoft Store
* Operating System and version: Windows 11, 21H2, build 22000.1219
* OS Language Settings: English (United States)
* TUMOnline Default Language: English

**Comment by COM8** [comment]
@Saydemr thanks for reporting this bug. I fixed it and a new version of the app should be available by the end of the week.

**Comment by COM8** [comment]
New release: https://github.com/TUM-Dev/Campus-UWP/releases/tag/v.2.5.0.0
